export const weeklyCalisthenicsPlan = {
  title: 'Weekly Calisthenics Plan',
  emoji: '🗓️',
  equipment: 'Home + Pull-up Bar',
  goal:
    'Build strength, improve pull-ups, develop an athletic physique, and move toward visible abs.',
  workoutTime: '~35–45 min',
  restGuidelines: ['40–60 sec for most exercises', '90 sec for pull-ups'],
  days: [
    {
      id: 'monday',
      label: 'Monday',
      focus: 'Push + Core',
      warmup: [
        'Jumping jacks × 1 min',
        'Arm circles × 30 sec forward + backward',
        'Shoulder rolls × 30 sec',
        'Easy push-ups × 10',
      ],
      workout: [
        'Push-ups — 4 × 12–15',
        'Pike push-ups — 4 × 8–12',
        'Diamond push-ups — 3 × 6–10',
        'Incline push-ups — 2 sets near failure',
      ],
      core: [
        'Plank — 3 × 60 sec',
        'Leg raises — 3 × 12–15',
        'Hollow hold — 3 × 20–30 sec',
      ],
      executableRoutine: [
        { name: 'Pushups', reps: 14, tension: 2, reset: 0.5, gif: '' },
        { name: 'Pushups', reps: 14, tension: 2, reset: 0.5, gif: '' },
        { name: 'Pushups', reps: 14, tension: 2, reset: 0.5, gif: '' },
        { name: 'Pushups', reps: 14, tension: 2, reset: 0.5, gif: '' },
        { name: 'Pushups', reps: 10, tension: 3, reset: 0.6, gif: '' },
        { name: 'Pushups', reps: 10, tension: 3, reset: 0.6, gif: '' },
        { name: 'Pushups', reps: 10, tension: 3, reset: 0.6, gif: '' },
        { name: 'Pushups', reps: 10, tension: 3, reset: 0.6, gif: '' },
        { name: 'Diamond Pushups', reps: 8, tension: 2, reset: 0.6, gif: '' },
        { name: 'Diamond Pushups', reps: 8, tension: 2, reset: 0.6, gif: '' },
        { name: 'Diamond Pushups', reps: 8, tension: 2, reset: 0.6, gif: '' },
        { name: 'Incline Pushups', reps: 12, tension: 2, reset: 0.6, gif: '' },
        { name: 'Incline Pushups', reps: 12, tension: 2, reset: 0.6, gif: '' },
        { name: 'Plank', reps: 1, tension: 60, reset: 10, gif: '' },
        { name: 'Plank', reps: 1, tension: 60, reset: 10, gif: '' },
        { name: 'Plank', reps: 1, tension: 60, reset: 10, gif: '' },
        { name: 'Leg Raises', reps: 14, tension: 2, reset: 0.5, gif: '' },
        { name: 'Leg Raises', reps: 14, tension: 2, reset: 0.5, gif: '' },
        { name: 'Leg Raises', reps: 14, tension: 2, reset: 0.5, gif: '' },
        { name: 'Plank', reps: 1, tension: 25, reset: 8, gif: '' },
        { name: 'Plank', reps: 1, tension: 25, reset: 8, gif: '' },
        { name: 'Plank', reps: 1, tension: 25, reset: 8, gif: '' },
      ],
      routineSettings: { sets: 1, restBetweenSet: 0, restBetweenEx: 45, prepTime: 10 },
    },
    {
      id: 'tuesday',
      label: 'Tuesday',
      focus: 'Pull',
      warmup: [
        'Dead hang × 30 sec',
        'Scapular pull-ups × 2 × 5',
        'Shoulder circles',
      ],
      workout: [
        'Pull-ups — 6 sets',
        'Example: 2,2,1,1,1,1',
        'Negative pull-ups — 4 × 3',
        'Lower for 5–8 seconds',
        'Dead hang — 3 × 45 sec',
        'Bicep curls — 4 × 12–20',
        'Towel rows (if possible) — 3 × 10–15',
      ],
      core: [],
      executableRoutine: [
        { name: 'Pull-ups', reps: 2, tension: 2, reset: 1, gif: '' },
        { name: 'Pull-ups', reps: 2, tension: 2, reset: 1, gif: '' },
        { name: 'Pull-ups', reps: 1, tension: 2, reset: 1, gif: '' },
        { name: 'Pull-ups', reps: 1, tension: 2, reset: 1, gif: '' },
        { name: 'Pull-ups', reps: 1, tension: 2, reset: 1, gif: '' },
        { name: 'Pull-ups', reps: 1, tension: 2, reset: 1, gif: '' },
        { name: 'Negative Pull-ups', reps: 3, tension: 6, reset: 1, gif: '' },
        { name: 'Negative Pull-ups', reps: 3, tension: 6, reset: 1, gif: '' },
        { name: 'Negative Pull-ups', reps: 3, tension: 6, reset: 1, gif: '' },
        { name: 'Negative Pull-ups', reps: 3, tension: 6, reset: 1, gif: '' },
        { name: 'Dead Hang', reps: 1, tension: 45, reset: 10, gif: '' },
        { name: 'Dead Hang', reps: 1, tension: 45, reset: 10, gif: '' },
        { name: 'Dead Hang', reps: 1, tension: 45, reset: 10, gif: '' },
        { name: 'Bicep Curls', reps: 16, tension: 2, reset: 0.6, gif: '' },
        { name: 'Bicep Curls', reps: 16, tension: 2, reset: 0.6, gif: '' },
        { name: 'Bicep Curls', reps: 16, tension: 2, reset: 0.6, gif: '' },
        { name: 'Bicep Curls', reps: 16, tension: 2, reset: 0.6, gif: '' },
        { name: 'Towel Rows', reps: 12, tension: 2, reset: 0.6, gif: '' },
        { name: 'Towel Rows', reps: 12, tension: 2, reset: 0.6, gif: '' },
        { name: 'Towel Rows', reps: 12, tension: 2, reset: 0.6, gif: '' },
      ],
      routineSettings: { sets: 1, restBetweenSet: 0, restBetweenEx: 60, prepTime: 10 },
    },
    {
      id: 'wednesday',
      label: 'Wednesday',
      focus: 'Legs + Core',
      warmup: [
        'High knees × 1 min',
        'Bodyweight squats × 20',
        'Leg swings',
      ],
      workout: [
        'Squats — 4 × 20',
        'Assisted Bulgarian split squats — 4 × 10 each leg',
        'Walking lunges — 3 × 20 steps',
        'Glute bridges — 4 × 20',
        'Calf raises — 4 × 30',
      ],
      core: ['Plank — 2 × 60 sec', 'Leg raises — 2 × 15'],
      executableRoutine: [
        { name: 'Bodyweight Squats', reps: 20, tension: 2, reset: 0.5, gif: '' },
        { name: 'Bodyweight Squats', reps: 20, tension: 2, reset: 0.5, gif: '' },
        { name: 'Bodyweight Squats', reps: 20, tension: 2, reset: 0.5, gif: '' },
        { name: 'Bodyweight Squats', reps: 20, tension: 2, reset: 0.5, gif: '' },
        { name: 'Bulgarian Split Squats', reps: 20, tension: 2, reset: 0.6, gif: '' },
        { name: 'Bulgarian Split Squats', reps: 20, tension: 2, reset: 0.6, gif: '' },
        { name: 'Bulgarian Split Squats', reps: 20, tension: 2, reset: 0.6, gif: '' },
        { name: 'Bulgarian Split Squats', reps: 20, tension: 2, reset: 0.6, gif: '' },
        { name: 'Lunges', reps: 20, tension: 2, reset: 0.5, gif: '' },
        { name: 'Lunges', reps: 20, tension: 2, reset: 0.5, gif: '' },
        { name: 'Lunges', reps: 20, tension: 2, reset: 0.5, gif: '' },
        { name: 'Glute Bridges', reps: 20, tension: 3, reset: 0.5, gif: '' },
        { name: 'Glute Bridges', reps: 20, tension: 3, reset: 0.5, gif: '' },
        { name: 'Glute Bridges', reps: 20, tension: 3, reset: 0.5, gif: '' },
        { name: 'Glute Bridges', reps: 20, tension: 3, reset: 0.5, gif: '' },
        { name: 'Calf Raises', reps: 30, tension: 1.5, reset: 0.4, gif: '' },
        { name: 'Calf Raises', reps: 30, tension: 1.5, reset: 0.4, gif: '' },
        { name: 'Calf Raises', reps: 30, tension: 1.5, reset: 0.4, gif: '' },
        { name: 'Calf Raises', reps: 30, tension: 1.5, reset: 0.4, gif: '' },
        { name: 'Plank', reps: 1, tension: 60, reset: 10, gif: '' },
        { name: 'Plank', reps: 1, tension: 60, reset: 10, gif: '' },
        { name: 'Leg Raises', reps: 15, tension: 2, reset: 0.5, gif: '' },
        { name: 'Leg Raises', reps: 15, tension: 2, reset: 0.5, gif: '' },
      ],
      routineSettings: { sets: 1, restBetweenSet: 0, restBetweenEx: 45, prepTime: 10 },
    },
    {
      id: 'thursday',
      label: 'Thursday',
      focus: 'Push + Core',
      repeatLabel: 'Same routine.',
      executableRoutineSource: 'monday',
    },
    {
      id: 'friday',
      label: 'Friday',
      focus: 'Pull',
      repeatLabel: 'Same routine.',
      executableRoutineSource: 'tuesday',
    },
    {
      id: 'saturday',
      label: 'Saturday',
      focus: 'Legs + Core',
      repeatLabel: 'Same routine.',
      executableRoutineSource: 'wednesday',
    },
    {
      id: 'sunday',
      label: 'Sunday',
      focus: 'Rest',
      repeatLabel: 'Walk 🚶 · Stretch · Relax · No hard training.',
      warmup: [],
      workout: [],
      core: [],
      isRestDay: true,
    },
  ],
  progressionRules: [
    {
      exercise: 'Push-ups',
      when: 'When you can do 4 × 15 comfortably',
      moveTo: 'Move to decline push-ups (feet elevated).',
    },
    {
      exercise: 'Pull-ups',
      when: 'When your max reaches 5 reps, start sets of 3. At 8 reps, start adding more total reps.',
      moveTo: '',
    },
    {
      exercise: 'Pike Push-ups',
      when: 'When you hit 4 × 12',
      moveTo: 'Elevate your feet on a chair.',
    },
    {
      exercise: 'Bulgarian Split Squats',
      when: 'When 4 × 15 each leg is easy',
      moveTo: 'Reduce hand support, then progress toward unassisted versions.',
    },
  ],
};

export function resolveWeeklyPlanDay(dayId) {
  const byId = Object.fromEntries(weeklyCalisthenicsPlan.days.map((entry) => [entry.id, entry]));
  const currentDay = byId[dayId] || byId.monday;

  if (!currentDay.executableRoutineSource) {
    return currentDay;
  }

  const sourceDay = byId[currentDay.executableRoutineSource];
  return {
    ...currentDay,
    warmup: sourceDay?.warmup || [],
    workout: sourceDay?.workout || [],
    core: sourceDay?.core || [],
    executableRoutine: sourceDay?.executableRoutine || [],
    routineSettings: sourceDay?.routineSettings || { sets: 1, restBetweenSet: 0, restBetweenEx: 45, prepTime: 10 },
  };
}
